function [] = chapter_4_figures() 
% Generate figures for chapter 4, outputting them as EPS files in the current directory. Assumes that chapter_4_tests has been
% run and that its output files are in the Matlab path. Note that not every figure generated by this script is used in the thesis.
% The mapping from figure labels in the thesis to files generated by this script is as follows:
% 

    figWidth = 20;
    figHeight = 14;

    disp('Generating plots for QPTN1 tests...');
%     qptn1SampleMeanPlots = PTN.test.plot_ptn_learn_sample_accuracy_mean('qptn1_sample_results.json', 'QPTN 1', [1e-8-eps, 1]);
%     for i=1:numel(qptn1SampleMeanPlots)
%         qptn1SampleMeanPlots{i}.Units = 'centimeters';
%         qptn1SampleMeanPlots{i}.Position = [0 0 figWidth figHeight];
%         print(qptn1SampleMeanPlots{i}, sprintf('qptn1_sample_mean_plot_%d.eps', i), '-depsc');
%     end

    disp('Generating plots for QPTN2 tests...');
%     qptn2SampleMeanPlot = PTN.test.plot_ptn_learn_sample_accuracy_mean_alltargets('qptn2_sample_results.json', 'QPTN 2', [1e-8-eps, 1]);
%     qptn2SampleMeanPlot.Units = 'centimeters';
%     qptn2SampleMeanPlot.Position = [0 0 figWidth figHeight];
%     print(qptn2SampleMeanPlot, 'qptn2_sample_mean.eps', '-depsc');
%     qptn2SampleBoxPlots = PTN.test.plot_ptn_learn_sample_accuracy_box('qptn2_sample_results.json', 'QPTN 2', [1e-5-eps, 1]);
%     for i=1:numel(qptn2SampleBoxPlots)
%        qptn2SampleBoxPlots{i}.Units = 'centimeters';
%        qptn2SampleBoxPlots{i}.Position = [0 0 figWidth figHeight];
%        print(qptn2SampleBoxPlots{i}, sprintf('qptn2_sample_box_plot_%d.eps', i), '-depsc');
%     end
    
    disp('Generating plots for QPTN3 tests...');
%     qptn3SampleMeanPlot = PTN.test.plot_ptn_learn_sample_accuracy_mean_alltargets('qptn3_sample_results.json', 'QPTN 3', [1e-8-eps, 1]);
%     qptn2SampleMeanPlot.Units = 'centimeters';
%     qptn2SampleMeanPlot.Position = [0 0 figWidth figHeight];
%     print(qptn3SampleMeanPlot, 'qptn3_sample_mean.eps', '-depsc');

    disp('Done generating plots.');
end